version: '3'

services:
  app:
    container_name: app
    build: 
      context: node
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - app-network
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]      
      timeout: 10s
      retries: 10

  nginx:
    container_name: nginx
    build:
      context: nginx
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  app-network:
    driver: bridge